import numpy as np
from StateVector import StateVector, InterpolationIndex

# -------------------------------------------------------------------
# NOTE: Don't forget that density(\rho) is a function of Pressure(P) and Temperature(T)
# Therefore, you need to remember to take those derivatives!
# Remember: \rho_{half} = Utilities.equation_of_state(P_{half},T_{half}) = \mu (P_{k+1}-P_{k})/(T_{k+1}-T_{k})
# -------------------------------------------------------------------

# NOTE: dm = m_{k+1}-m_{k}. Assume this is a constant (ie. shells sizes are the same throughout)

# NOTE: This file houses the sub-matrix generator for the Jacobian, and the Jacobian calculator
# There are 16 functions, with each one dedicated to a particular sub block

# -------------------------------------------------------------------
# NOTE: We expect all submatrix calculations to have the same signature:
# interpolated_values: a 5x(k-1) dimensional array containing the interpolated values of the state vector (plus density)
#   Generated by StateVector.interpolate_all()

# Output: We expect the output of each function to be a nxn matrix
# where n = (k-1), where k is the number of shells
# Stitching everything together should give a 4(k-1) square matrix
# To take into account the boundary conditions, we use stitch_vector on the state vector
# -------------------------------------------------------------------


# Difference equation for radius
# (r_{k+1}-r_{k})/(dm)- 1/(4*pi*r^{2}_{half}* \rho_{half})

# -------------------------------------------------------------------
# NOTE: For now, just use random matrices so that I can work on the rest  of the pipeline (Can't invert 0 matrix!)
# -------------------------------------------------------------------


# Radius
def Jac_block_00(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Pressure
def Jac_block_01(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Temperature
def Jac_block_02(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Luminosity
def Jac_block_03(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Difference equation for Pressure
# (P_{k+1}-P_{k})/(dm) +  (dm/2)/(4*pi*r^{4}_{half})

# Radius
def Jac_block_10(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Pressure
def Jac_block_11(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Temperature
def Jac_block_12(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Luminosity
def Jac_block_13(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Difference equation for Temperature
# (T_{k+1}-T_{k})/(dm)+ \kappa_0 \rho_{half}* L_{half}/r^{4}_{half}/T^{6.5}_{half}

# Radius
def Jac_block_20(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Pressure
def Jac_block_21(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Temperature
def Jac_block_22(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Luminosity
def Jac_block_23(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Difference equation for luminosity
# (L_{k+1}-L_{k})/(dm)- \epsilon_0 \rho_{half}*T_{half}^{4}=g

# Radius
def Jac_block_30(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Pressure
def Jac_block_31(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Temperature
def Jac_block_32(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

# Luminosity
def Jac_block_33(interpolated, dm, constants):
    output = np.random.rand(interpolated.shape[1],interpolated.shape[1])
    return output

def gen_Jacobian(state_vector: StateVector, constants):
    """
        Outputs the Jacobian of the residual function needed for Newton-Raphson
        Input:
            state_vector: Instance of StateVector
        Output:
            nxn Jacobian matrix, where n = 4*(k-1), where k is the number of shells
            Need to use Utilities.stich_vector to make this Jacobian useful in NR method
    """
    interpolated_values = state_vector.interpolate_all(constants)
    dm = 1/state_vector.n_shells

    J00 = Jac_block_00(interpolated_values, dm, constants)
    J01 = Jac_block_01(interpolated_values, dm, constants)
    J02 = Jac_block_02(interpolated_values, dm, constants)
    J03 = Jac_block_03(interpolated_values, dm, constants)
    J0 = np.concatenate([J00, J01, J02, J03], axis=1)

    J10 = Jac_block_10(interpolated_values, dm, constants)
    J11 = Jac_block_11(interpolated_values, dm, constants)
    J12 = Jac_block_12(interpolated_values, dm, constants)
    J13 = Jac_block_13(interpolated_values, dm, constants)
    J1 = np.concatenate([J10, J11, J12, J13], axis=1)

    J20 = Jac_block_20(interpolated_values, dm, constants)
    J21 = Jac_block_21(interpolated_values, dm, constants)
    J22 = Jac_block_22(interpolated_values, dm, constants)
    J23 = Jac_block_23(interpolated_values, dm, constants)
    J2 = np.concatenate([J20, J21, J22, J23], axis=1)

    J30 = Jac_block_30(interpolated_values, dm, constants)
    J31 = Jac_block_31(interpolated_values, dm, constants)
    J32 = Jac_block_32(interpolated_values, dm, constants)
    J33 = Jac_block_33(interpolated_values, dm, constants)
    J3 = np.concatenate([J30, J31, J32, J33], axis=1)
    
    out = np.concatenate([J0,J1,J2,J3], axis=0)
    return out


if __name__=="__main__":
    pass